# Generated by Django 4.2.17 on 2025-01-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_playerregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerregistration',
            unique_together={('tournament', 'player_email')},
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_game',
        ),
    ]
