# Generated by Django 4.2.17 on 2025-01-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_playerregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerregistration',
            unique_together={('tournament', 'player_name')},
        ),
    ]
