# Generated by Django 4.2.16 on 2025-02-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_playerregistration_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='age',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_age',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_weight_category',
        ),
        migrations.AddField(
            model_name='player',
            name='player_age',
            field=models.CharField(choices=[('U15', 'Under 15'), ('U17', 'Under 17'), ('U20', 'Under 20'), ('U25', 'Under 25'), ('+25', 'Over 25')], default='U15', max_length=4),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='age_group',
            field=models.CharField(choices=[('U15', 'Under 15'), ('U17', 'Under 17'), ('U20', 'Under 20'), ('U25', 'Under 25'), ('+25', 'Over 25')], default='15', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='division',
            field=models.CharField(default='Lightweight', editable=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='weight_category',
            field=models.CharField(choices=[('Lightweight', 'Lightweight (up to 60 kg)'), ('Middleweight', 'Middleweight (61-80 kg)'), ('Heavyweight', 'Heavyweight (81-100 kg)'), ('Super Heavyweight', 'Super Heavyweight (over 100 kg)')], default='LightWeight', max_length=20),
            preserve_default=False,
        ),
    ]
