# Generated by Django 4.2.19 on 2025-03-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_player_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_age',
            new_name='age_group',
        ),
        migrations.AlterUniqueTogether(
            name='playerregistration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='player',
            name='category',
        ),
        migrations.RemoveField(
            model_name='player',
            name='weight',
        ),
        migrations.AddField(
            model_name='player',
            name='weight_category',
            field=models.CharField(blank=True, choices=[('Lightweight', 'Lightweight (up to 60 kg)'), ('Middleweight', 'Middleweight (61-80 kg)'), ('Heavyweight', 'Heavyweight (81-100 kg)'), ('Super Heavyweight', 'Super Heavyweight (over 100 kg)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerregistration',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.player'),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='division',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='playerregistration',
            unique_together={('tournament', 'player')},
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_email',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='player_name',
        ),
        migrations.RemoveField(
            model_name='playerregistration',
            name='weight_category',
        ),
    ]
